### PR TITLE
Proj/xld

### PR DESCRIPTION
**Pull request by antsr**
Major change:
- Move ZI devices to a new drivers, which share the base ZI driver.
  - many parameter names changed from `quex... to qas...`

Minor changes:
- Many print statements removed
- Many lines reformatted to fit 80 chars
- RamseyAddPulseAnalysis and measure_ramsey_add_pulse modified
- ZI PQSC driver added
- Add Surface-7 measurements
  - multi_parity_multi_round_seq and ro_dynamic_phase_seq only work with the XLD setup (UHF names hardcoded in dummy readout pulses)
- Support for single-shot acquisition in 2-qubit rb
- custom segment filter and option to extract pauli set from raw data added to MultiQubit_SingleShot_Analysis
- MeasurementInducedDephasingAnalysis and measure_measurement_induced_dephasing rewritten
- Unused sweep functions deleted
- Add PQSC trigger source option to HDAWG in Pulsar

### CODE REVIEW

**Comment by antsr** [comment]
Please have a quick look if you think it is fine to merge
@stephlazar 
@chellings 
@michele-cc or @jo3141

**Review by chellings — APPROVED** [review]
no bugs encountered when using this branch for measurements on the XLD setup on 2020-01-15 (afternoon)

**Comment by antsr** [comment]
@jo3141 @michele-cc could one of you still give a thumbs up to merge this?

**Review by stephlazar — APPROVED** [review]
@jo3141 and @michele-cc please review the alpha zz measurement + analysis code and let us know if this works for you (no major changes). If yes, then we would merge.

**Comment by chellings** [comment]
Please note that someone pushed 4 new commits from the XLD setup this morning. I had committed them in order to save my current state of work, but had intentionally not pushed them due to the open pull request: these changes include aspects that might be necessary to discuss. In particular:
- My quick fix to get dummy_UHFQC working again might not be the best way of doing it. I restored some parameter files that were deleted because they are no longer needed by the real UHFQC, but they are still needed by the dummy UHFQC. So the cleaner solution would be to change the dummy UHFQC such that it is compatible with the new ZI way of storing parameters.
- Adding an update parameter to gen.load_settings() was a functionality that I found useful, but someone with more pycQED experience might want to check whether including the new functionality of update=False in load_settings makes sense or whether the same thing exists already in some other function that I do not know.

**Comment by antsr** [comment]
Yes, they were accidentally pushed from the XLD setup. We looked over the changes with @stephlazar and they seemed reasonable. 
Comment on the `dummy_UHFQC`: you should not need this class anymore, as with the latest ZI pycqed drivers you can initialize their instruments with `server='emulator'`. We should delete the `dummy_UHFQC` class from the qudev_master branch.

**Pull request merged**
