### PR TITLE
Closing opened HDF files throughout PyCQED

### PR DESCRIPTION
**Pull request by stephlazar**
Makes sure HDF files are closed wherever they are opened in PycQED such that we (hopefully) avoid more data file corruption issues.

Moves the statement that closes data file in BaseAnalysis from the end of run_analysis to the end of extract_data. Some classes do not call run_analysis, but they usually have to call extract_data. It also makes the most sense that we close the file after extracting from it, not at the end of analysis.

FYI @antsr

### CODE REVIEW

**Review by chellings — CHANGES_REQUESTED** [review]
BaseDataAnalysis()
In case of multiple data files (e.g., Singleshot_Readout_Analysis_Qutrit) this only closes the last datafile.

load_settings_onto_instrument()
Has this change been tested? On my system, this makes the function crash: after closing, ins_group is a <Closed HDF5 group> object from which you can't read. Also note that this function already has an f.close() at the very end.
I wonder why we need load_settings_onto_instrument() anyways. The difference to load_settings() seems to be that it can load settings from instr A onto instr B, but the function cannot handle data types that we now load via eval() in load_settings(). It might make sense to include the functionality of loading from a different instrument into load_settings() in order to not have to maintain two functions.

load_settings_onto_instrument_v2()
I suspect that this change would cause the same issues as in load_settings_onto_instrument(), but I cannot test it since the functions crashes already earlier with "Unable to open object (object 'Snapshot' doesn't exist)". I wonder what the purpose of this function is.

load_T1_T2_pulse_length()
The change looks okay, but the attributes nr_sigma and gauss_sigma that we try to get in this function do not exist on my setup. Is this function up to date and used anywhere?

get_param_value_from_file()
This change is okay.

get_qb_channel_map_from_hdf()
This change is okay.

get_qb_thresholds_from_file()
The change looks okay, but the attribute RO_acq_weight_function_I that we try to get in this function does not exist on my setup. Is this function up to date and used anywhere?

compare_instrument_settings_timestamp()
This change is okay. However, I just realized that the function compare_instrument_settings_timestamp() no longer works since "from numpy import array" was deleted in the analysis cleanup pull request. This is needed by the eval statement used to read some data types from the hdf file. This should line should be added again (preferably with a comment "from numpy import array  # DO not remove. Used in eval(array(...))" like in other instances).

**Comment by stephlazar** [comment]
Hey, thanks a lot for looking so carefully and for the detailed comments! I will comment on some of them here.

First, I did not aim to clean up deprecated functions with this pull request. So it's a good observation that we do not use load_settings_onto_instrument() or load_settings_onto_instrument_v2(). These were the original functions by Delft before I wrote our own, which is the load_settings that we use. The entire randomized_benchmarking_analysis file (where load_T1_T2_pulse_length() is) is deprecated. This was the original analysis that I wrote during my Master thesis but which now doesn't work anymore given code upgrades. 
Since you brought it up, I will clean this up.

I did not notice the f.close() in load_settings_onto_instrument(). Thanks! Should be fine as it was.

The snapshot that load_settings_onto_instrument_v2() is trying to load from used to be the state of the station object as a JSON-compatible dict the MC saved to the HDF file (lines 1155-1158). However, it made our files a couple MB large so we removed it. But I think it's good to keep this function in case we might want to add it back.

Thanks for catching the missing from numpy import array statement!

Thanks for catching that not all files are closed in BaseAnalysis for multiple timestamps. This also made me realize making the data file an attribute of the class is useless if we close it.

**Review by nathlacroix — APPROVED** [review]
In an ideal coding world, the closing of the file would be done in a try/except clause to ensure the file is closed even if something goes wrong within the function before reaching the line where the datafile is closed. But I would understand if you don't change it all now and the suggested code is already better than what was there before. Maybe it could be worth to have such a clause in the one or two most common places we use it.

**Comment by stephlazar** [comment]
@nathlacroix I have now implemented your great suggestion with the try/except statements. Maybe you can have a quick look.

**Review by chellings — APPROVED** [review]

**Pull request merged**
