### PR TITLE
bugfix/2D measurements with int_log_det

### PR DESCRIPTION
**Pull request by stephlazar**
This pull request fixes the 2D sweeps with the integration logging detector used for ssro measurements.
What I had done before was in the right direction, but the acq_data_len_scaling parameter that I had introduced for this was not added in the correct places.

- [x] Tested on virtual setup

- [x] Has been running on S17 setup for a couple of months. Single qubit RB data acquired with this fix.

### CODE REVIEW

**Comment by antsr** [comment]
Changes look reasonable, but as you say, this should be tested on a real setup 👍

**Comment by stephlazar** [comment]
I realized now that the 1D ssro measurement was not fixed in the previous commit. The measurement worked because of the line 369 in MC in this branch, where it catches any exceptions and just moves on. This looks like bad design so we might consider dealing with it properly at some point. So the 1D measurement worked but the sweep points column was all 0. I now also added the acq_data_len_scaling parameter in another 2 places to make it not go into this exception and hence have the correct sweep points.

**Comment by stephlazar** [comment]
I added code to raise a warning whenever an exception is found in MC.measure_hard() DATA STORING BLOCK section.

**Comment by stephlazar** [comment]
I think it is time to merge this fix. It has been used for the last 2 months on the XLD setup with no issues. SSRO single qubit RB was acquired with this fix.

**Review by chellings — APPROVED** [review]
Looks good and was tested successfully

**Pull request merged**
