### PR TITLE
Features for algorithmic layer (block, circuit_builder, improved sequence plotting)

### PR DESCRIPTION
**Pull request by chellings**
This pull request contains a first version of the features proposed by @nathlacroix  and @chellings , which will be presented in the algorithmic layer meeting with @antsr @stephlazar @christiankraglundandersen @MichKe95 @jo3141  and other interested participants.

Changes proposed in this pull request:
- new module block defining the Block class (to group pulses)
- new module circuit_builder defining the CircuitBuilder class (to conveniently create pulses, blocks, etc. from e.g., lists of operations)
- improved plotting functionality in Segment (possibility to group pulses by qubits to easily visualize pulse sequences that implement algorithms)
- a bugfix in measure_arbitrary_sequence (to allow easy testing of an algorithm on a real setup)

Most of the code is new and should not interfere with any other existing code. (The changes in Segment.plot() affect existing code, but the new arguments are optional.)

We thus propose that these changes are merged as soon as possible, so that everyone who is interested can start using the new features. Further improvements will be made available in a further pull requests in the future.

Inviting @antsr and @stephlazar to review

### CODE REVIEW

**Comment by nathlacroix** [comment]
@chellings will you add the demo notebook? Thanks!

**Comment by stephlazar** [comment]
image (3)

**Comment by stephlazar** [comment]
Based on yesterday's presentation, I will approve this pull request. I remember a few things were mentioned that can still be added/improved but I think we should have this in the master asap such that others can use it.

**Review by stephlazar — APPROVED** [review]

**Review by antsr — APPROVED** [review]
Looks good to me.

**Pull request merged**
