### PR TITLE
start cleanup of pulses, fix small bug in resolve_Z_gates

### PR DESCRIPTION
**Pull request by antsr**
Important! Non-backwards compatible changes requiring updating of variables when reloading from old files:
* DRAG pulse amplitude changed when using mixer calibration.
* Readout pulse phase_lock meaning flipped. For readout with UHF, we now need to have phase-lock False. The corresponding `QuDev_transmon` parameter is `ro_phase_lock`.

Overview of changes: 

* New structure of pulse library: pulse.py defines the base pulse class,
  while pulse_library.py defines the different pulse implementations.
  New module variable `pulse_libraries` in pulse.py allows to split the
  pulse definitions across multiple files.

* clean up `apply_modulation` and `SSB_DRAG_pulse` according to new standards.

* Normalization of mixer correction predistorition changed such that the
  total power of the signal remains constant. **This means that Rabi
  amplitudes have to be updated where mixer calibration is used.**

* unify meaning of `phase_lock = True` property of pulses. If phase lock is
  true, then the phase reference point is the start of the algorithm, not
  the start of the pulse. It was like this for DRAG pulse before, but the
  meaning was opposite for readout pulses. **This means that the value of**
  `qb.ro_phase_lock` **was flipped.**

* Remove old `element` code that did not work any more anyways, therefore 
  partly addresses #9 

* Make sequences that were not ported to new pulse gen framework raise
  `NotImplementedError`.

* Fix bug in `resolve_Z_gates` that caused the virtual z rotations to be
  multiple-counted if the segment timing is resolved multiple times, for
  example when plotting a sequence that was uploaded to the AWG already.

* All changes tested on a virtual AWG setup by running the chevron sequence.

* Remains to be done: cleanup of other pulse shapes.

### CODE REVIEW

**Comment by stephlazar** [comment]
"Normalization of mixer correction predistorition changed such that the
total power of the signal remains constant. This means that Rabi
amplitudes have to be updated where mixer calibration is used."

We always needed to redo Rabi after mixer calibration. Do we need to do something additional now?

**Comment by stephlazar** [comment]
I also think it would make sense to test the RB sequence, because there we use VZ pulses.
Do you think it would make sense to also test that every single class in pulse_library that you modified still works?

**Comment by stephlazar** [comment]
Otherwise, this is great work, thanks for taking the time! I especially liked the pulse_libraries logic and how the global variable is populated; I already stole it for analysis_v3 :p

**Comment by antsr** [comment]
> We always needed to redo Rabi after mixer calibration. Do we need to do something additional now?

No, the tuneup procedure remains the same. What I meant is that at the time you merge these updates, you have to rerun Rabi if you used mixer calibration.

**Comment by antsr** [comment]
> I also think it would make sense to test the RB sequence, because there we use VZ pulses.

I can test that. Are `QuDev_transmon.measure_randomized_benchmarking` and `multi_qubit_module.measure_two_qubit_randomized_benchmarking` the relevant functions?

**Comment by stephlazar** [comment]
Yes, those are the relevant RB functions. But i think you only need the sequences no? Those are single_qubit_tek_seq_elts.randomized_renchmarking_seqs and multi_qubit_tek_seq_elts.two_qubit_randomized_benchmarking_seqs

**Comment by antsr** [comment]
I have now manually tested that the updated branch give the same waveforms for two-qubit randomized benchmarking. 
The waveforms for drive pulses were 112 samples (47 ns) longer in the new version for some reason, though due to extra zeros at the end.

**Comment by stephlazar** [comment]
Do you mean that the RB sequence is 47ns longer, or that each drag pulse is 47ns longer?
If it is the former, I think I would like to understand why the RB sequence is now longer. It must be that the changes made to the VZ pulse now causes the RB sequence code to result in some additional delays (there is a block of code there which handles simultaneous playback of pulses on different channels; maybe something there does not work anymore). 

I could look into it, but not sure exactly when I will have time.

**Comment by stephlazar** [comment]
I could look into it, but not sure exactly when I will have time.

**Comment by antsr** [comment]
The waveform length issue is weird, but seems like it is not related to this pull request. 
I created a new issue for the waveform length problem: #39
My opinion is that this pull-request could be now merged.

**Comment by stephlazar** [comment]
OK thanks for looking into it! Then I would approve this pull request

**Review by stephlazar — APPROVED** [review]
Looks good!

**Review by chellings — APPROVED** [review]
Looks good, but it is important to point out to everyone the implications of the new drive amplitude scaling and the necessary changes in the readout pulse instrument settings.

After having adapted those settings, everything seemed to work correctly, but a bit more testing on the measurement setups might be good.

**Comment by antsr** [comment]
@MichKe95 @christiankraglundandersen @jo3141 Please ping here or let me know that you are aware of the implications this pull request will have on reloading parameters from old files before I merge it.

**Comment by MichKe95** [comment]
Looks good, also from my side! Thanks for the effort!

**Comment by MichKe95** [comment]
Looks good also from my side!

**Pull request merged**
